name: Bump version and last modified time

on: 
  workflow_dispatch:
      title:
        required: false
        default: 'Notification from Github actions'
        description: title of notification
        type: string
      message:
        required: false
        default: ''
        description: description of notification
        type: string
      url:
        required: false
        default: ''
        description: link of notification
        type: string


  workflow_call:
    inputs:
      title:
        required: false
        default: 'Notification from Github actions'
        description: title of notification
        type: string
      message:
        required: false
        default: ''
        description: description of notification
        type: string
      url:
        required: false
        default: ''
        description: link of notification
        type: string

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - name: Prep payload
        id: prep
        run: echo "body={\"value1\": $TITLE, \"value2\": $DESC, \"value3\": $URL}" >>"$GITHUB_ENV"
        env: 
          TITLE: ${{ inputs.title }}
          DESC: ${{ inputs.message }}
          URL: ${{ inputs.url }}
            
      - name: Webhook
        uses: joelwmale/webhook-action@v2
        with:
          url: ${{ secrets.WEBHOOK_URL }}
          body: ${{ env.body }}
